version: "3"

services:
  asuka:
    container_name: asuka
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - seq
#      - mysql
#    links:
#      - seq
#      - mysql
#
#  seq:
#    container_name: seq
#    restart: unless-stopped
#    image: datalust/seq:latest
#    environment:
#      ACCEPT_EULA: Y
#
#  mysql:
#    container_name: mysql
#    image: mysql
#    restart: always
#    ports:
#      - 8080:8080
#    environment:
#      MYSQL_HOST: ${DB_HOST}
#      MYSQL_USERNAME: ${DB_USERNAME}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_SCHEMA}
