version: '3.8'

volumes:
  db_data:

services:
  asuka:
    container_name: asuka
    image: asuka
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: src/Asuka/Dockerfile
    # Application might continue crashing until
    # dependent service(s) fully initialize
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
