version: "3.9"

services:
  asuka:
    container_name: asuka
    restart: always
    build: .
#    depends_on:
#      - mysql
#    links:
#      - mysql
#
#  mysql:
#    container_name: mysql
#    image: mysql
#    restart: always
#    ports:
#      - 8080:8080
#    environment:
#      MYSQL_HOST: ${DB_HOST}
#      MYSQL_USERNAME: ${DB_USERNAME}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_SCHEMA}
